# Generated by Django 2.0.4 on 2018-04-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_department_designation_execom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='execom',
            old_name='department',
            new_name='chapter',
        ),
    ]
