# Generated by Django 2.0.4 on 2018-04-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180422_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chapter_name',
        ),
    ]
