# Generated by Django 2.0.4 on 2018-04-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180422_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execom',
            old_name='chapter',
            new_name='chapter_name',
        ),
    ]
