# Generated by Django 2.0.4 on 2018-04-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180422_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_name',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='execom',
            old_name='chapter_name',
            new_name='chapter',
        ),
    ]
