# Generated by Django 2.0.4 on 2018-04-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180422_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execom',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Chapter'),
        ),
        migrations.AlterField(
            model_name='execom',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Designation'),
        ),
    ]
