# Generated by Django 2.0.4 on 2018-04-22 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180422_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievment', models.CharField(max_length=300)),
                ('achievment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Achievment Date:')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/events/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='execom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/execom/'),
        ),
    ]
