# Generated by Django 2.0.4 on 2018-04-22 21:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180423_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigContent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Page Content')),
            ],
        ),
        migrations.AlterField(
            model_name='achievment',
            name='achievment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Achievment Date'),
        ),
    ]
