# Generated by Django 2.0.4 on 2018-04-25 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180423_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=300, verbose_name='Latest News')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on:')),
            ],
        ),
    ]
