# Generated by Django 2.0.4 on 2018-04-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_latestnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestnews',
            old_name='news',
            new_name='content',
        ),
    ]
