# Generated by Django 2.0.4 on 2018-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180425_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestNews',
            new_name='Update',
        ),
    ]
