# Generated by Django 2.0.4 on 2018-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180425_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create_date',
            new_name='event_date',
        ),
    ]
