# Generated by Django 2.0.4 on 2018-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180426_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/events/%Y/%m/%d/'),
        ),
    ]
