# Generated by Django 2.0.4 on 2018-04-26 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20180426_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='achievment',
            field=ckeditor.fields.RichTextField(verbose_name='Achievment'),
        ),
    ]
