# Generated by Django 2.0.4 on 2018-08-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20180901_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sig',
            name='members',
        ),
    ]
