# Generated by Django 2.0.4 on 2018-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_sig_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigmentor',
            name='sig',
        ),
        migrations.AddField(
            model_name='sig',
            name='members',
            field=models.ManyToManyField(to='web.SigMentor'),
        ),
    ]
