# Generated by Django 2.0.4 on 2018-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180901_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='SIG Name'),
            preserve_default=False,
        ),
    ]
