# Generated by Django 2.1.1 on 2018-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_sig_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/events/'),
        ),
        migrations.AlterField(
            model_name='sig',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/sigs/'),
        ),
    ]
