# Generated by Django 2.0.4 on 2018-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180902_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='execom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='execom/'),
        ),
        migrations.AlterField(
            model_name='sig',
            name='image',
            field=models.ImageField(null=True, upload_to='sigs/'),
        ),
    ]
