# Generated by Django 2.0.4 on 2018-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20180902_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.FileField(null=True, upload_to='events/'),
        ),
    ]
