# Generated by Django 2.0.4 on 2018-09-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_event_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='register_url',
            field=models.URLField(blank=True, max_length=100, verbose_name='Register Url'),
        ),
        migrations.AlterField(
            model_name='event',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
    ]
