# Generated by Django 2.0.4 on 2018-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20180929_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='execom',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='execom/'),
        ),
    ]
