# Generated by Django 2.0.4 on 2019-03-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_execom_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='team/')),
            ],
        ),
    ]
