# Generated by Django 2.0.4 on 2019-03-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_execom_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='execom',
            name='email',
            field=models.URLField(blank=True, null=True),
        ),
    ]
