# Generated by Django 2.0.4 on 2019-03-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_execom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execom',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
