# Generated by Django 2.0.4 on 2019-03-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
