# Generated by Django 2.0.4 on 2019-06-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_team_github'),
        ('web', '0028_auto_20190302_0752'),
    ]

    operations = [
    ]
