# Generated by Django 2.0.4 on 2019-09-08 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_chapter_chapter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='execom',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on:'),
        ),
    ]
