# Generated by Django 2.0.4 on 2019-09-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_execom_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_description',
        ),
    ]
