# Generated by Django 2.0.4 on 2019-10-14 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_chapter_chapter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='Title')),
                ('blog_content', models.TextField(verbose_name='Content')),
                ('blog_image', models.ImageField(null=True, upload_to='blogs/')),
                ('blog_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on:')),
                ('blog_by', models.CharField(max_length=100, verbose_name='By:')),
            ],
        ),
    ]
