# Generated by Django 2.0.4 on 2019-10-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20191015_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_by',
            field=models.CharField(max_length=100, verbose_name='Written By:'),
        ),
    ]
