# Generated by Django 2.0.4 on 2020-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20191017_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='execom',
            name='page_rank',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Frontend Rank'),
            preserve_default=False,
        ),
    ]
