# Generated by Django 2.0.4 on 2020-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20200128_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Visitor Counter')),
            ],
        ),
    ]
