# Generated by Django 2.0.4 on 2020-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Counter Name')),
                ('counter', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Visitor Counter')),
            ],
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
