# Generated by Django 2.0.4 on 2020-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20200202_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
