# Generated by Django 3.2.3 on 2021-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_delete_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='htmlData',
            field=models.TextField(blank=True, help_text='HTML data to be executed as is.'),
        ),
    ]
