# Generated by Django 3.2.3 on 2021-06-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_blog_htmldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='execom',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
