# Generated by Django 3.2.3 on 2021-06-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20210602_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='execom',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.branch'),
            preserve_default=False,
        ),
    ]
